export const PROVIDER_SYMBOLS = {
    ACCOUNT_CONFIG: 'TRAILMIXCMS_CMS_ACCOUNT_CONFIG',
    ACCOUNT_SCHEMA: 'TRAILMIXCMS_CMS_ACCOUNT_SCHEMA',
    ACCOUNT_SETUP: 'TRAILMIXCMS_CMS_ACCOUNT_SETUP',
    ACCOUNT_MAP_ENTITY: 'TRAILMIXCMS_CMS_ACCOUNT_MAP_ENTITY',

    ORGANIZATION_CONFIG: 'TRAILMIXCMS_CMS_ORGANIZATION_CONFIG',
    ORGANIZATION_SCHEMA: 'TRAILMIXCMS_CMS_ORGANIZATION_SCHEMA',
    ORGANIZATION_SETUP: 'TRAILMIXCMS_CMS_ORGANIZATION_SETUP',
    ORGANIZATION_MAP_ENTITY: 'TRAILMIXCMS_CMS_ORGANIZATION_MAP_ENTITY',

    AUTH_GUARD_HOOK: 'TRAILMIXCMS_CMS_AUTH_GUARD_HOOK',
    ORGANIZATION_DELETE_HOOK: 'TRAILMIXCMS_CMS_ORGANIZATION_DELETE_HOOK',
} as const;