enableScripts: false

npmScopes:
  trailmix-cms:
    npmPublishRegistry: "https://registry.npmjs.org"

packageExtensions:
  vite-plugin-vue-devtools@*:
    peerDependencies:
      vue: "*"
  vite-ssg@*:
    peerDependencies:
      unhead: "*"
