enableGlobalCache: false

enableScripts: false

npmMinimalAgeGate: 7d

npmScopes:
  trailmix-cms:
    npmPublishRegistry: "https://registry.npmjs.org"

packageExtensions:
  vite-ssg@*:
    peerDependencies:
      unhead: "*"
