name: Publish Docs

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Docs Site
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v6

      - name: 📦 Enable Corepack
        run: corepack enable

      - name: 🏗 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.1
          cache: yarn

      - name: 📦 Install dependencies
        working-directory: ./iac
        run: yarn install --immutable

      - name: 🔄 Pulumi Up
        uses: pulumi/actions@v6
        with:
          stack-name: prod
          command: up
          work-dir: ./iac
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}