name: Node.js Package

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.14.1
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn ci

      - run: cd ./packages/cms && yarn npm publish --access public
      - run: cd ./packages/db && yarn npm publish --access public
      - run: cd ./packages/models && yarn npm publish --access public
      - run: cd ./packages/utils && yarn npm publish --access public
      - run: cd ./packages/vue && yarn npm publish --access public