name: Snyk Security

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  snyk:
    name: Snyk scan
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'chore') }}
    steps:
      - uses: actions/checkout@v6

      - name: 📦 Enable Corepack
        run: corepack enable

      - name: 🏗 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install --immutable

      - name: 🔒 Snyk test
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --yarn-workspaces --strict-out-of-sync=false --severity-threshold=high
          command: test

      - name: 🔒 Snyk monitor
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --yarn-workspaces --strict-out-of-sync=false
          command: monitor
